# Generated by Django 4.1.5 on 2023-01-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_answer_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_state',
            new_name='pub_date',
        ),
    ]
